cluster.name: "docker-cluster"
node.name: es-master
network.host: 0.0.0.0
http.port: 9200
node.data: false
node.ingest: false
node.master: true
discovery.zen.minimum_master_nodes: 2
discovery.seed_hosts:
 - elasticsearch
 - elasticsearch2:9202
 - elasticsearch3:9203
# must use node.name
cluster.initial_master_nodes:
 - es-master
 - es-node2
 - es-node3
bootstrap.memory_lock: true

